# Generated by Django 5.0.14 on 2026-09-03 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("active", models.BooleanField(default=True)),
                (
                    "wish_priority",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="1 (low) to 5 (high)"
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("operating_hours", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeLocationEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.employee",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.location",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "location", "starts_on")},
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="allowed_locations",
            field=models.ManyToManyField(
                blank=True,
                through="people.EmployeeLocationEligibility",
                to="people.location",
            ),
        ),
    ]
