# Generated by Django 5.1.15 on 2026-09-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="allowed_locations",
            field=models.ManyToManyField(
                blank=True,
                through="people.EmployeeLocationEligibility",
                to="people.location",
                verbose_name="Allowed locations",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=160, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(blank=True, max_length=80, verbose_name="Role"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="wish_priority",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="1 (low) to 5 (high)", verbose_name="Wish priority"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=120, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="location",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="location",
            name="operating_hours",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Operating hours"
            ),
        ),
    ]
