# Generated by Django 5.1.15 on 2026-09-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("missing", "Missing report"),
                    ("pace", "Below pace"),
                    ("no_increase", "No increase"),
                ],
                max_length=20,
                verbose_name="Rule type",
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("critical", "Critical"),
                ],
                default="warning",
                max_length=12,
                verbose_name="Severity",
            ),
        ),
        migrations.AlterField(
            model_name="manageralert",
            name="explanation",
            field=models.TextField(verbose_name="Explanation"),
        ),
        migrations.AlterField(
            model_name="manageralert",
            name="manager_note",
            field=models.TextField(blank=True, verbose_name="Manager note"),
        ),
        migrations.AlterField(
            model_name="manageralert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("critical", "Critical"),
                ],
                default="warning",
                max_length=12,
                verbose_name="Severity",
            ),
        ),
        migrations.AlterField(
            model_name="manageralert",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("acknowledged", "Acknowledged"),
                    ("resolved", "Resolved"),
                    ("dismissed", "Dismissed"),
                ],
                default="open",
                max_length=16,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="performancereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("superseded", "Superseded"),
                    ("review", "Needs review"),
                ],
                default="accepted",
                max_length=12,
                verbose_name="Status",
            ),
        ),
    ]
