# Generated by Django 5.0.14 on 2026-09-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rosterwish",
            name="date_preference",
            field=models.CharField(
                choices=[
                    ("wanted", "Wanted"),
                    ("unwanted", "Unwanted"),
                    ("neutral", "No date preference"),
                ],
                default="neutral",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="rosterwish",
            name="preferred_weekdays",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Weekday numbers: Monday is 0, Sunday is 6.",
            ),
        ),
    ]
