# Generated by Django 5.0.14 on 2026-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0002_rosterwish_date_preference_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shifttemplate",
            old_name="required_headcount",
            new_name="max_headcount",
        ),
        migrations.AddField(
            model_name="shifttemplate",
            name="min_headcount",
            field=models.PositiveIntegerField(
                default=1, help_text="Minimum coverage required for this shift."
            ),
        ),
    ]
