# Generated by Django 5.0.14 on 2026-09-03 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        ("roster", "0003_remove_shifttemplate_required_headcount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shifttemplate",
            name="max_headcount",
            field=models.PositiveIntegerField(
                default=1, help_text="Maximum employees permitted on this shift."
            ),
        ),
        migrations.CreateModel(
            name="RosterGenerationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "Preview"),
                            ("applied", "Applied"),
                            ("invalid", "Invalid"),
                        ],
                        default="preview",
                        max_length=12,
                    ),
                ),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("summary", models.JSONField(default=dict)),
                ("diagnostics", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "roster_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_runs",
                        to="roster.rosterversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RosterGenerationProposalAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("wish_score", models.IntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="people.employee",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="people.location",
                    ),
                ),
                (
                    "generation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_assignments",
                        to="roster.rostergenerationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at", "employee__name"],
            },
        ),
    ]
