# Generated by Django 5.1.15 on 2026-09-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0004_alter_shifttemplate_max_headcount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rostergenerationrun",
            name="planning_starts_on",
            field=models.DateField(
                blank=True, help_text="First date the solver may change.", null=True
            ),
        ),
    ]
