# Generated by Django 5.1.15 on 2026-09-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("people", "0001_initial"), ("roster", "0005_rostergenerationrun_planning_starts_on")]

    operations = [
        migrations.CreateModel(
            name="RosterEmployeeTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_shifts", models.PositiveIntegerField(verbose_name="Target shifts")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="people.employee")),
                ("roster_version", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="employee_targets", to="roster.rosterversion")),
            ],
            options={"unique_together": {("roster_version", "employee")}},
        ),
    ]
