# Generated by Django 5.1.15 on 2026-09-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_alter_employee_active_and_more"),
        ("roster", "0006_rosteremployeetarget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absence",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved")],
                default="pending",
                max_length=12,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="rostergenerationrun",
            name="planning_starts_on",
            field=models.DateField(
                blank=True,
                help_text="First date the solver may change.",
                null=True,
                verbose_name="Planning starts on",
            ),
        ),
        migrations.AlterField(
            model_name="rosterversion",
            name="month",
            field=models.DateField(
                help_text="First day of the month", verbose_name="Month"
            ),
        ),
        migrations.AlterField(
            model_name="rosterversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("superseded", "Superseded"),
                ],
                default="draft",
                max_length=12,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="rosterwish",
            name="date_preference",
            field=models.CharField(
                choices=[
                    ("wanted", "Wanted"),
                    ("unwanted", "Unwanted"),
                    ("neutral", "No date preference"),
                ],
                default="neutral",
                max_length=12,
                verbose_name="Date preference",
            ),
        ),
        migrations.AlterField(
            model_name="rosterwish",
            name="preferred_weekdays",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Weekday numbers: Monday is 0, Sunday is 6.",
                verbose_name="Preferred weekdays",
            ),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="break_minutes",
            field=models.PositiveIntegerField(default=0, verbose_name="Break minutes"),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="end_time",
            field=models.TimeField(verbose_name="End time"),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="people.location",
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="max_headcount",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Maximum employees permitted on this shift.",
                verbose_name="Maximum staff",
            ),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="min_headcount",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Minimum coverage required for this shift.",
                verbose_name="Minimum staff",
            ),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="name",
            field=models.CharField(max_length=80, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="start_time",
            field=models.TimeField(verbose_name="Start time"),
        ),
    ]
